version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lerna bootstrap
            - run: yarn lerna exec -- yarn test --scope=app-shell